// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function useIsMounted(param) {
  var ref = React.useRef(false);
  React.useEffect((function () {
          ref.current = true;
          return (function (param) {
                    ref.current = false;
                    return /* () */0;
                  });
        }), ([]));
  return ref;
}

exports.useIsMounted = useIsMounted;
/* react Not a pure module */
